import { Component } from '@angular/core';
import { Wizard } from './model/wizard';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'wordwizard';
  word1: string | undefined;
  meaning1: string | undefined;

  constructor() { }
  CoinArray = [new Wizard('abberant', ' - deviant from normal'),
  new Wizard('abeyance', ' - suspension or hold the door'),
  new Wizard( 'abstemious' ,' - normal diet or moderate') ,
  new Wizard( 'aesthetic',' - realting to beauty or art') ,
  new Wizard( 'alacrity', '- eagerness,speed, exited for change') ,
  new Wizard( 'alleviate', '- relieve; improve partially') ,
  new Wizard( 'amalgamate', '- combined into whole like power rangers') ,
  new Wizard( 'ambiguous', '- unclear or doubtful') ,
  new Wizard( 'ambivalence', '- having conflicting emotions') ,
  new Wizard( 'arcane', ' - secret: understood by few; mysterious ') ,
  new Wizard( 'ameliorate', '- to improve') ,
  new Wizard( 'anachronism', '- somethig out of proper time') ,
  new Wizard( 'analogous', '- comparable-- which can be compared to') ,
  new Wizard( 'anarchy', '- absence of govt:: state of disorder') ,
  new Wizard( 'anomalous', '- irregular::strange behaviour ::: deviating from norm') ,
  new Wizard( 'apathy', '- indifference') ,
  new Wizard( 'antipathy', '- dislike') ,
  new Wizard( 'apprise', '- to inform') ,
  new Wizard( 'banal', '- commanplace: something which is very common') ,
  new Wizard( 'belie', '- misrepresent:: giving false impression') ,
  new Wizard( 'bombastic', '- over wordly:: with less meaning') ,
  new Wizard( 'boorish', '- rude:: insensitive:: I apologize for my boorish behaviour') ,
  new Wizard( 'burgeon', '- flourish :: increase rapidly') ,
  new Wizard( 'burnish', '-to polish:: i burnished my reputation..') ,
  new Wizard( 'buttress', '- reinforce :: support') ,
  new Wizard( 'approbation', '- praise: approval:: highest approbatian a soldier can receive') ,
  new Wizard( 'arduous', '- extremely difficult:: laborious') ,
  new Wizard( 'artless', '- guileless:: somrthing natural') ,
  new Wizard( 'ascetic', '- practicing self denial') ,
  new Wizard( 'aspersion', '- slander:: false rumour') ,
  new Wizard( 'assiduous', '- hard working') ,
  new Wizard( 'attenuate', '- weaken') ,
  new Wizard( 'audacious', '- bold : daring') ,
  new Wizard( 'austere', '- severe :: strict') ,
  new Wizard( 'aver', '- affirm:: declare to be true:: confirms') ,
  new Wizard( 'cacophonous', '- unpleasant: harsh sounding:: I find his music cacophonous') ,
  new Wizard( 'cant', '- hypocritical :: language of a particular group') ,
  new Wizard( 'capricious', '- ficke :: sudden changes') ,
  new Wizard( 'castigation', '- punishment: criticism:: I received a lot of castigation in school') ,
  new Wizard( 'catalyst', '- responsible for causing change') ,
  new Wizard( 'chicanery', '- trickery: fraud:: police found a financial chicanery near my home') ,
  new Wizard( 'coagulate', '-thicken:: blood begins to coagulate after a wound') ,
  new Wizard( 'commensurate', '- proportional:: speed is commensurate to distance') ,
  new Wizard( 'compendium', '- breif: summary:: The compendium about my life') ,
  new Wizard( 'decorum', '- proper behaviour') ,
  new Wizard( 'deference', '- respect:: regard for anothers wish::  he addressed her with deference due to her age') ,
  new Wizard( 'delineate', '- describe :: potray precisely') ,
  new Wizard( 'demotic', '- denoting to people') ,
  new Wizard( 'demur', '- express doubt:: raise objections') ,
  new Wizard( 'denigrate', '- kinchaparuchu :: paruvutiyadam :: he denigrate his brother') ,
  new Wizard( 'complaisant', '- overly polite: willing to please') ,
  new Wizard( 'conciliatory', '- overcoming distrust or hostility enemy): ') ,
  new Wizard( 'concomitant', '- existing concurrently:: naturally accompanying :: "he loved travel, with all its concomitant worries" ') ,
  new Wizard( 'confound', '- to baffle: perplex: mix up:: confused ') ,
  new Wizard( 'contentious', '- causing an argument:  controversial') ,
  new Wizard( 'conundrum', '- riddle:: puzzle with no solution') ,
  new Wizard( 'convoluted', '- twisted: complicated :: tenet has a convoluted plot') ,
  new Wizard( 'cosmology', '- study of universe') ,
  new Wizard( 'covert', '- hidden : secret :: this is covert mission') ,
  new Wizard( 'craven', '- cowardly :: refusing to fight is not a craven act') ,
  new Wizard( 'credence', '- believability:: acceptance of something as true') ,
  new Wizard( 'denouement', '- outcome :: climax of play or movie') ,
  new Wizard( 'derivate', '- unoriginal:: derived from his work') ,
  new Wizard( 'desiccate', '- dried out') ,
  new Wizard( 'desultory', '- lack of plan,purpose, intrest :: people left dancing in a desultory fashion') ,
  new Wizard( 'diaphanous', '-light, delicate :: transparent') ,
  new Wizard( 'diatride', '- bitter verbal attack') ,
  new Wizard( 'dichotomy', '- division between two opposite items') ,
  new Wizard( 'diffidence', '- shyness, lack of self confidence :: i say this with some diffidence') ,
  new Wizard( 'diffuse', '- spread out') ,
  new Wizard( 'disabuse', '- free from misconception :: he quickly disabused my thoughts on big bang') ,
  new Wizard( 'discordant', '- disagreeing') ,
  new Wizard( 'discrepancy', '- diff between something') ,
  new Wizard( 'discrete', '- distinct') ,
  new Wizard( 'disingenuous', '- not candid:: dishonest') ,
  new Wizard( 'disinterested', '- not influenced by advantage :: no intrest') ,
  new Wizard( 'dismiss', '- reject :: put away') ,
  new Wizard( 'disparage', '- belittle:: he always disparage his brother') ,
  new Wizard( 'disparate', '- not similar') ,
  new Wizard( 'dissemble', '- disguise their feelings:: an honest person with no need to dissemble') ,
  new Wizard( 'disseminate', '- to spread scatter:: diffuse') ,
  new Wizard( 'dissolution', '- come to end:: disintegrate') ,
  new Wizard( 'dissonance', '- alck of harmony :: party has dissonance among their candidates') ,
  new Wizard( 'doctrinaire', '- person who cannot compromise') ,
  new Wizard( 'dogmatic', '- stating opinions without proof') ,
  new Wizard( 'ebullient', '- excited: enthusiastic :: she sounded ebullient and happy') ,
  new Wizard( 'eclectic', '- selecting from various sources :: vit offers eclectic mix of courses') ,
  new Wizard( 'effete', '- weakened: this was an effete protest') ,
  new Wizard( 'efficacy', '- efficiency') ,
  new Wizard( 'impertinent', '- rude : no respect') ,
  new Wizard( 'effrontery', '- shameless act: rude') ,
  new Wizard( 'elegy', '- poem or song expressing greif, sorrow') ,
  new Wizard( 'lamentation', '- greig, sorrow') ,
  new Wizard( 'elicit', '- drawout: provoke :: i tried to elicit a laugh from batman') ,
  new Wizard( 'embellish', '-making more attractive by adding details') ,
  new Wizard( 'emaciated', '- thin : wasted') ,
  new Wizard( 'empirical', '- derived from observation :: actual') ,
  new Wizard( 'emulate', '- imitate : copy:: mos rulers tried to emulate alexander') ,
  new Wizard( 'endemic', '- belonging to specific area') ,
  new Wizard( 'enervated', '- weaken ') ,
  new Wizard( 'ephemeral', '- lasting for a very short time') ,
  new Wizard( 'equanimity', '- calmness:: doctors are trained to maintain their equanimity') ,
  new Wizard( 'equivocate', '- intentionally using vague language to conceal truth') ,
  new Wizard( 'erudite', '- having great knowledge:: learned') ,
  new Wizard( 'esoteric', '- hard to understand:: known only to few:: doctors using esoteric writing') ,
  new Wizard( 'euphenism', '- use of agreeable or inoffensive language in place of offensive or unpleasant lang') ,
  new Wizard( 'exacerbate', '- to make things worse') ,
  new Wizard( 'exulpate', '- proving someone not guilty') ,
  new Wizard( 'execrable', '- extremely bad :: unpleasant') ,
  new Wizard( 'exhort', '- strongly encourage:: urge someone to do something') ,
  new Wizard( 'exigency', '- crisis:: urgent requirements') ,
  new Wizard( 'existential', '- relating to existence') ,
  new Wizard( 'extant', '- in existence') ,
  new Wizard( 'extraneous', '- not essential:: irrelevant:: extreme origin') ,
  new Wizard( 'extrapolation', '- estimating by projecting known information') ,
  new Wizard( 'facetious', '- humorous') ,
  new Wizard( 'fallacious', '- misleading:: going based on false idea') ,
  new Wizard( 'fatuous', '- silly :: foolish comments') ,
  new Wizard( 'felicitous', '- appropriate :: well chosen') ,
  new Wizard( 'fidelity', '- loyalty') ,
  new Wizard( 'fledgling', '- beginner:: emerging :: fledgling sun') ,
  new Wizard( 'foment', '- incite undesirable or violent behaviour):: they accused him of fomenting political unrest') ,
  new Wizard( 'forestall', '- delay :: to prevent') ,
  new Wizard( 'formidable', '- threatening') ,
  new Wizard( 'fractious', '- irritable :: quarrelsome') ,
  new Wizard( 'frugality', '- saving and not wasting') ,
  new Wizard( 'fulminate', '- expressing loudly :: rage:: he fulminated against his actions') ,
  new Wizard( 'gainsay', '- deny:: oppose:: no one can gainsay his hardwork') ,
  new Wizard( 'garrulous', '- very talkative:: wordy') ,
  new Wizard( 'grandiloquent', '- over wordy :: bombastic :: pompous') ,
  new Wizard( 'gregarious', '- fond of being in company:: sociable') ,
  new Wizard( 'guilelss', '- free of cunning :: artless') ,
  new Wizard( 'gullible', '- easily ::fooled') ,
  new Wizard( 'harangue', '- long aggresive speech:: diatride:: coach gave a harangue speech to team about their mistakes') ,
  new Wizard( 'heterodox', '- unorthodox:: not confirming with accepted standards') ,
  new Wizard( 'histrionic', '- dramatic:: theatrical') ,
  new Wizard( 'homily', '- too long :: tedious moralizing speech') ,
  new Wizard( 'homogeneous', '- composed of identical parts') ,
  new Wizard( 'hyperbole', '- purpuseful exaggeration for effect') ,
  new Wizard( 'iconoclastic', '- criticizing cherished beliefs') ,
  new Wizard( 'ideological', '- based on ideas especially concerning political and economic system') ,
  new Wizard( 'idolatry', '- idol worship:: execessive worship') ,
  new Wizard( 'igneous', '- produced by fire :: volcanic') ,
  new Wizard( 'immutable', '- unchangable') ,
  new Wizard( 'impassive', '- showing no emotion') ,
  new Wizard( 'impede', '- to hinder: obstruct :: delay') ,
  new Wizard( 'impermeable', '- impossible to penetrate') ,
  new Wizard( 'imperturbable', '- not easily disturbed') ,
  new Wizard( 'impervious', '- impossible to penetrate:: not affected by') ,
  new Wizard( 'implacable', '- unable to be pleased') ,
  new Wizard( 'implausible', '- unbelievable') ,
  new Wizard( 'implicit', '-implied :: suggested but not stated :: indirect') ,
  new Wizard( 'inadvertenly', '- carelessly:: unintentionally') ,
  new Wizard( 'inchoate', '- not fully formed') ,
  new Wizard( 'incongruity', '- state of not fitting:: there is incongruity between poems solemn and its light hearted theme') ,
  new Wizard( 'indeterminate', '- uncertain:: not exactly known') ,
  new Wizard( 'indigence', '- poverty') ,
  new Wizard( 'indolent', '- wanting to avoid:: lazy') ,
  new Wizard( 'ineluctable', '- inevitable : cannot be avoided') ,
  new Wizard( 'inert', '- unable to move :: inactive') ,
  new Wizard( 'ingenuous', '- unsuspecting :: truthful') ,
  new Wizard( 'inherent', '- existing permanently') ,
  new Wizard( 'innocuous', '- harmless') ,
  new Wizard( 'insensible', '- unconscious :: unresponsive') ,
  new Wizard( 'insinuate', '- to suggest:: say indirectly ') ,
  new Wizard( 'insipid', '- lacking in flavour, intrest :: tasteless') ,
  new Wizard( 'insularity', '- narrow mindedness :: lack of intrest in others idea..') ,
  new Wizard( 'intractable', '- not easily managed') ,
  new Wizard( 'intransigence', '- stubborn:: refuse to compromise') ,
  new Wizard( 'inundate', '-overwhelm') ,
  new Wizard( 'inured', '- accustomed:: used to : harden:: These children are inuredto violence') ,
  new Wizard( 'invective', '- verbal abuse') ,
  new Wizard( 'irascible', '- easily angered') ,
  new Wizard( 'irresolute', '- un sure of how to act') ,
  new Wizard( 'jocose', '- playful:: fond of joking') ,
  new Wizard( 'juxtapose', '- place side by side') ,
  new Wizard( 'kudos', '-fame : honor received for achievement') ,
  new Wizard( 'laconic', '- using very few words:: the laconic reply suggested he has no intrest in the topic') ,
  new Wizard( 'lassitude', '- state of physical or mental weakness') ,
  new Wizard( 'latent', '-present but hidden') ,
  new Wizard( 'levity', '- light manner : he finds an element of levity even in a most serious subject') ,
  new Wizard( 'lethargic', '- inactive :dull') ,
  new Wizard( 'limpid', '- clear: transparent') ,
  new Wizard( 'loquacious', '- talkative') ,
  new Wizard( 'lucid', '- bright :: clear :: ') ,
  new Wizard( 'lustrous', '- shining') ,
  new Wizard( 'magnanimity', '- generosity : nobility') ,
  new Wizard( 'malinger', '- exaggerate incapacity or illness :: to avoid malinger company requires doctors proof before taking leave') ,
  new Wizard( 'malleable', '- easily influenced:: capable of being shaped by pounding') ,
  new Wizard( 'maverick', '- individualist :: unorthodox minded person') ,
  new Wizard( 'mendacious', '- dishonest') ,
  new Wizard( 'meretricious', '- easily attracted but has no value') ,
  new Wizard( 'metamorphosis', '- change :: transformation') ,
  new Wizard( 'metaphysics', '- branch of philosophy investigating nature of reality') ,
  new Wizard( 'meticulous', '- precise: very clear:: great attention to detail') ,
  new Wizard( 'misanthrope', '- one who hates humanity') ,
  new Wizard( 'misogynist', '- one who hates women') ,
  new Wizard( 'mitigate', '- making less pain,severe..') ,
  new Wizard( 'mollify', '- reduce anger of someone:: soothe') ,
  new Wizard( 'morose', '- badtempered') ,
  new Wizard( 'mundane', '- dull,:: wordly as opposed to spiritual') ,
  new Wizard( 'neophyte', '- beginner to a subject or activity') ,
  new Wizard( 'obdurate', '- stubborn') ,
  new Wizard( 'obsequious', '- obedient :: they were served by obsequious waiters') ,
  new Wizard( 'obviate', '- to aniticipate and prevent:: parachute can be used to obviate disaster') ,
  new Wizard( 'occlude', '- stop, block:: full makeup can occlude pores') ,
  new Wizard( 'officious', '- people who are ready to offer unasked advice:: too helpful') ,
  new Wizard( 'onerous', '- burdensome: he found his duties onerous') ,
  new Wizard( 'opprobrium', '- disgrace : harsh criticism') ,
  new Wizard( 'oscillate', '- move back and forth') ,
  new Wizard( 'ostentatious', '- trying to attract attraction:: show of') ,
  new Wizard( 'paragon', '- model of excellence or perfection') ,
  new Wizard( 'partisan', '- strong support to party..:: become prejudiced') ,
  new Wizard( 'pathological', ' - involving physical or mental disease') ,
  new Wizard( 'paucity', ' - scarcity: shortage') ,
  new Wizard( 'pedantic', ' - person who is excessively concerned with  accuracy, and precision') ,
  new Wizard( 'pellucid', ' - transparant:: easily understood') ,
  new Wizard( 'pencahnt', ' - strong liking for something::inclination') ,
  new Wizard( 'penury', ' - extreme poverty') ,
  new Wizard( 'perfidious', ' - faithless:; disloyal') ,
  new Wizard( 'perfunctory', ' - carried out without real interest, feeling, or effort') ,
  new Wizard( 'permeable', ' - penetrable') ,
  new Wizard( 'pervasive', ' - spreading widely throughout an area') ,
  new Wizard( 'phlegmatic', ' - calm in temparament:: sluggish') ,
  new Wizard( 'piety', ' - devotion:: related to religious') ,
  new Wizard( 'plasticity', ' - consition of being able to be shaped or formed') ,
  new Wizard( 'platitute', ' - a statement, that has been used too often to be interesting or thoughtful') ,
  new Wizard( 'plethora', ' -excess..overabundance') ,
  new Wizard( 'pragmatic', ' -dealing with things srealistically ::practical') ,
  new Wizard( 'precarious', ' - uncertain') ,
  new Wizard( 'precipitate', ' - cause to happen suddenlt,unexpectedly:; ') ,
  new Wizard( 'precursor', ' - forerunner:: predeccessor') ,
  new Wizard( 'presumptuos', ' -  failing to observe the limits of what is appropriate ::rude:: arrogant') ,
  new Wizard( 'prevaricate', ' - lie:: quibble') ,
  new Wizard( 'probity', ' - honesty') ,
  new Wizard( 'problamatic', ' - causing problem') ,
  new Wizard( 'prodigal', ' - spending money wastely: extravagant: lavish :: ') ,
  new Wizard( 'profound', ' - very great or intense: deep') ,
  new Wizard( 'proliferate', ' - increase rapidly') ,
  new Wizard( 'propensity', ' - inclination: tendency to behave in a particular way') ,
  new Wizard( 'propitiate', ' - win over:appease') ,
  new Wizard( 'propriety', ' - conformity to conventionally accepted standards :: he always behaved with the utmost propriety') ,
  new Wizard( 'proscribe', ' - forbid:: ban') ,
  new Wizard( 'qualified', ' - limited:: having complied with a purpose') ,
  new Wizard( 'quiescent', ' - inactive: still') ,
  new Wizard( 'rarefied', ' - refined: thinner') ,
  new Wizard( 'recalcitrant', ' - having an uncooperative attitude towards authority') ,
  new Wizard( 'recant', ' - denial of a previously published opinion or belief.') ,
  new Wizard( 'recondite', ' -  little known; abstruse:: obscure') ,
  new Wizard( 'refractory', ' - stubborn :: unmanageable') ,
  new Wizard( 'refute', ' - disprove: contradict') ,
  new Wizard( 'relegate', ' - going to inferior position: portugal relegated from champions league') ,
  new Wizard( 'reproach', ' - blame;: find fault with') ,
  new Wizard( 'reprobate', ' - an unprincipled person:: villian: rogue') ,
  new Wizard( 'repudiate', ' - refuse to accept; reject') ,
  new Wizard( 'rescind', ' - to cancel: revoke: repeal') ,
  new Wizard( 'resolution', ' - determination: resolve') ,
  new Wizard( 'reticent', ' -not revealing:: introvert ') ,
  new Wizard( 'sage', ' - wise') ,
  new Wizard( 'salacious', ' - lustful') ,
  new Wizard( 'salubrious', ' - healthy') ,
  new Wizard( 'salutary', ' - producing good effects; beneficial') ,
  new Wizard( 'sanction', ' - approve: ratify') ,
  new Wizard( 'sartorial', ' - relating to tailoring, clothes, or style of dress.') ,
  new Wizard( 'satiate', ' - satisfy') ,
  new Wizard( 'sensual', ' - relating to or involving gratification of the senses and physical, especially sexual, pleasure.') ,
  new Wizard( 'sentient', ' - able to perceive or feel things.') ,
  new Wizard( 'skeptic', ' - one who doubts') ,
  new Wizard( 'solicitous', ' - concerned :: eager: attentive') ,
  new Wizard( 'soporifuc', ' - which causes sleep') ,
  new Wizard( 'specious', ' -  plausible, but actually wrong: misleading') ,
  new Wizard( 'sporadic', ' - occurring at irregular intervals or places:: scattered') ,
  new Wizard( 'stigma', ' -  mark of disgrace:: the stigma of having gone to prison will always be with me') ,
  new Wizard( 'stipulate', ' - specifying as essential condition') ,
  new Wizard( 'stolid', ' - showing little emotion') ,
  new Wizard( 'striated', ' - marked with long, thin : narrow:: an expensively outfitted kitchen with striated wood cabinets') ,
  new Wizard( 'substantiate', ' - provide evidence to support or prove the truth of') ,
  new Wizard( 'subsume', ' - include or absorb ') ,
  new Wizard( 'supersede', ' - replace :: to displace as antiquated old fashioned)::"the older models of car have now been superseded') ,
  new Wizard( 'supposition', ' - a belief held without proof : assumption') ,
  new Wizard( 'tacit', ' - understood or implied without being stated :: your silence may be taken to mean tacit agreement') ,
  new Wizard( 'taciturn', ' - reserved or uncommunicative in speech; saying little.') ,
  new Wizard( 'tangential', ' - going off topic') ,
  new Wizard( 'tautology', ' - unnecessary repetition') ,
  new Wizard( 'tenuous', ' - very weak or slight.') ,
  new Wizard( 'tirade', ' - a long, angry speech of criticism') ,
  new Wizard( 'torpor', ' - a state of physical or mental inactivity; lethargy') ,
  new Wizard( 'tortuous', ' - full of twists and turns') ,
  new Wizard( 'tractable', ' - obedient:: managable') ,
  new Wizard( 'transgression', ' - trespassing or violating law or rule') ,
  new Wizard( 'truculence', ' - aggressive : ferocity') ,
  new Wizard( 'turgid', ' - swollen:: tediously pompous bombastic') ,
  new Wizard( 'untenable', ' - undefendable:: not able to be maintained or defended against attack or objection.') ,
  new Wizard( 'vacillate', ' - waver between different opinions or actions:: oscillating between opinions') ,
  new Wizard( 'vapid', ' - tasteless:: dull') ,
  new Wizard( 'venerate', ' - honor : respect') ,
  new Wizard( 'veracious', ' - truthful :: accurate') ,
  new Wizard( 'verbose', ' - using or expressed in more words than are needed: wordy') ,
  new Wizard( 'viable', ' - practicable:: capable of developing') ,
  new Wizard( 'viscous', ' - thick:: sticky :: syrup is so viscous') ,
  new Wizard( 'vitiate', ' - spoil :: impair quality') ,
  new Wizard( 'vituperative', ' - bitter :: abusive') ,
  new Wizard( 'volatile', ' - liable to change rapidly and unpredictably') ,
  new Wizard( 'whimsical', ' - fanciful:: unpredictable') ,
  new Wizard( 'zealot', ' - a person who is fanatical and uncompromising in pursuit of their religious, political, or other ideals.')];
  num=0;
word(){
  this.num=Math.floor(Math.random()*305);
  this.word1=this.CoinArray[this.num].word;
}
meaning(){
  this.meaning1=this.CoinArray[this.num].meaning;
}
}
